# Generated by Django 5.0.3 on 2024-04-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='c_code',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='код верификации'),
        ),
    ]
