# Generated by Django 5.0.3 on 2024-04-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_c_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='c_code',
            new_name='v_code',
        ),
    ]
