# Generated by Django 5.0.3 on 2024-04-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_c_code_user_v_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='v_code',
        ),
    ]
