# Generated by Django 4.2 on 2024-04-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogwrite',
            name='author',
        ),
    ]
