# Generated by Django 4.2 on 2024-04-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_blogwrite_author_product_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('cancel_product_publication', 'Can cancel product publication'), ('change_product_description', 'Can change product description'), ('change_product_category', 'Can change product category')), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
